name: Java CI with Maven and Allure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Build with Maven
        run: mvn clean test

      - name: Download Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.16.0/allure-2.16.0.tgz
          tar -zxvf allure-2.16.0.tgz

      - name: Generate Allure report
        run: allure-2.16.0/bin/allure generate target/allure-results --clean -o target/allure-report

      - name: Publish Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/allure-report
