name: Run Tests

on:
  push:
    branches:
      - HW6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'

      - name: Build with Maven
        run: mvn clean test

      - name: Generate Allure report
        run: allure generate --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/allure-report
